Module7 task2
htmlacademy-javascript/2189499-kekstagram-27 pull request #6
Opened 2022-10-23 21:57 UTC by collagememorycollage

2022-10-25 19:44 UTC, 0snilcy requested changes
Плюс пропадает скролл после закрытия попапа.

2022-10-25 19:44 UTC, 0snilcy commented on js/fullPhoto.js
> +
Это зачем оставил?

2022-10-25 19:44 UTC, 0snilcy commented on js/fullPhoto.js
> +console.log(arrayOfPictures);
Логи не нужно пушить

2022-10-25 19:44 UTC, 0snilcy commented on js/fullPhoto.js
> +    socialComments.forEach((element, index) => {
Нужно итерировать по сгенерированному массиву комментариев и на основе данные уже создавать ноду.
Затем все их вставлять.
Ты же существующие ноды заполняешь данными, это некорректно.

2022-10-26 19:24 UTC, Satsukevich-Dzmitry commented on js/utils.js
> +const isEscKeydow = (evt) => ent.key === 'Escape'
Тут опечатка, ent вместо evt

2022-10-26 19:26 UTC, Satsukevich-Dzmitry commented on js/renderPhoto.js
> +const hiddenPhoto = function() {
https://up.htmlacademy.ru/javascript/27/criteries#b6
должен быть глагол в названии функции, а не прилагательное. В переменной hiddenPhoto можно было бы хранить картинку, которую ты спрятал, но не функцию, которая ее прячет)

2022-10-26 19:28 UTC, Satsukevich-Dzmitry commented on js/utils.js
> +const isEscKeydow = (evt) => ent.key === 'Escape'
Функцию стоит назвать по другому, не очень понятно что за слово keydow :)

2022-10-27 16:25 UTC, Satsukevich-Dzmitry approved these changes

2022-10-27 16:25 UTC, merged